import '../models/element.dart';

const List<ChemElement> kElements = [
  ChemElement(
    atomicNumber: 1, symbol: 'H', name: 'Hydrogen',
    atomicMass: 1.008, category: 'Nonmetal',
    shells: [1], configuration: '1s¹',
    valenceElectrons: 1, period: '1', group: '1',
    funFact: 'Most abundant element in the universe. Forms H₂O with oxygen.',
  ),
  ChemElement(
    atomicNumber: 2, symbol: 'He', name: 'Helium',
    atomicMass: 4.003, category: 'Noble gas',
    shells: [2], configuration: '1s²',
    valenceElectrons: 2, period: '1', group: '18',
    funFact: 'A completely full first shell makes helium the most stable element.',
  ),
  ChemElement(
    atomicNumber: 3, symbol: 'Li', name: 'Lithium',
    atomicMass: 6.941, category: 'Alkali metal',
    shells: [2, 1], configuration: '1s² 2s¹',
    valenceElectrons: 1, period: '2', group: '1',
    funFact: 'The lightest metal, used extensively in rechargeable batteries.',
  ),
  ChemElement(
    atomicNumber: 4, symbol: 'Be', name: 'Beryllium',
    atomicMass: 9.012, category: 'Alkaline earth metal',
    shells: [2, 2], configuration: '1s² 2s²',
    valenceElectrons: 2, period: '2', group: '2',
    funFact: 'Found in gemstones like emerald and aquamarine.',
  ),
  ChemElement(
    atomicNumber: 5, symbol: 'B', name: 'Boron',
    atomicMass: 10.811, category: 'Metalloid',
    shells: [2, 3], configuration: '1s² 2s² 2p¹',
    valenceElectrons: 3, period: '2', group: '13',
    funFact: 'Used in pyrotechnics to produce a distinctive green color.',
  ),
  ChemElement(
    atomicNumber: 6, symbol: 'C', name: 'Carbon',
    atomicMass: 12.011, category: 'Nonmetal',
    shells: [2, 4], configuration: '1s² 2s² 2p²',
    valenceElectrons: 4, period: '2', group: '14',
    funFact: 'Tetravalent carbon is the backbone of all organic chemistry and life.',
  ),
  ChemElement(
    atomicNumber: 7, symbol: 'N', name: 'Nitrogen',
    atomicMass: 14.007, category: 'Nonmetal',
    shells: [2, 5], configuration: '1s² 2s² 2p³',
    valenceElectrons: 5, period: '2', group: '15',
    funFact: 'Makes up about 78% of Earth\'s atmosphere as N₂ gas.',
  ),
  ChemElement(
    atomicNumber: 8, symbol: 'O', name: 'Oxygen',
    atomicMass: 15.999, category: 'Nonmetal',
    shells: [2, 6], configuration: '1s² 2s² 2p⁴',
    valenceElectrons: 6, period: '2', group: '16',
    funFact: 'Highly electronegative. Two lone pairs give water its bent shape.',
  ),
  ChemElement(
    atomicNumber: 9, symbol: 'F', name: 'Fluorine',
    atomicMass: 18.998, category: 'Halogen',
    shells: [2, 7], configuration: '1s² 2s² 2p⁵',
    valenceElectrons: 7, period: '2', group: '17',
    funFact: 'The most reactive and electronegative of all elements.',
  ),
  ChemElement(
    atomicNumber: 10, symbol: 'Ne', name: 'Neon',
    atomicMass: 20.180, category: 'Noble gas',
    shells: [2, 8], configuration: '1s² 2s² 2p⁶',
    valenceElectrons: 8, period: '2', group: '18',
    funFact: 'A full octet — neon does not form any chemical bonds naturally.',
  ),
  ChemElement(
    atomicNumber: 11, symbol: 'Na', name: 'Sodium',
    atomicMass: 22.990, category: 'Alkali metal',
    shells: [2, 8, 1], configuration: '1s² 2s² 2p⁶ 3s¹',
    valenceElectrons: 1, period: '3', group: '1',
    funFact: 'Extremely reactive soft metal that must be stored in oil.',
  ),
  ChemElement(
    atomicNumber: 12, symbol: 'Mg', name: 'Magnesium',
    atomicMass: 24.305, category: 'Alkaline earth metal',
    shells: [2, 8, 2], configuration: '1s² 2s² 2p⁶ 3s²',
    valenceElectrons: 2, period: '3', group: '2',
    funFact: 'Essential for photosynthesis as the central atom of chlorophyll.',
  ),
  ChemElement(
    atomicNumber: 13, symbol: 'Al', name: 'Aluminum',
    atomicMass: 26.982, category: 'Post-transition metal',
    shells: [2, 8, 3], configuration: '1s² 2s² 2p⁶ 3s² 3p¹',
    valenceElectrons: 3, period: '3', group: '13',
    funFact: 'The most abundant metal in Earth\'s crust, widely used in recycling.',
  ),
  ChemElement(
    atomicNumber: 14, symbol: 'Si', name: 'Silicon',
    atomicMass: 28.085, category: 'Metalloid',
    shells: [2, 8, 4], configuration: '1s² 2s² 2p⁶ 3s² 3p²',
    valenceElectrons: 4, period: '3', group: '14',
    funFact: 'The semiconductor heart of modern electronics and computer chips.',
  ),
  ChemElement(
    atomicNumber: 15, symbol: 'P', name: 'Phosphorus',
    atomicMass: 30.974, category: 'Nonmetal',
    shells: [2, 8, 5], configuration: '1s² 2s² 2p⁶ 3s² 3p³',
    valenceElectrons: 5, period: '3', group: '15',
    funFact: 'Essential for life, forming the backbone of DNA and ATP.',
  ),
  ChemElement(
    atomicNumber: 16, symbol: 'S', name: 'Sulfur',
    atomicMass: 32.06, category: 'Nonmetal',
    shells: [2, 8, 6], configuration: '1s² 2s² 2p⁶ 3s² 3p⁴',
    valenceElectrons: 6, period: '3', group: '16',
    funFact: 'Known since antiquity, often called "brimstone" in old texts.',
  ),
  ChemElement(
    atomicNumber: 17, symbol: 'Cl', name: 'Chlorine',
    atomicMass: 35.45, category: 'Halogen',
    shells: [2, 8, 7], configuration: '1s² 2s² 2p⁶ 3s² 3p⁵',
    valenceElectrons: 7, period: '3', group: '17',
    funFact: 'One electron short of a full shell — very reactive, forms NaCl with sodium.',
  ),
  ChemElement(
    atomicNumber: 18, symbol: 'Ar', name: 'Argon',
    atomicMass: 39.948, category: 'Noble gas',
    shells: [2, 8, 8], configuration: '1s² 2s² 2p⁶ 3s² 3p⁶',
    valenceElectrons: 8, period: '3', group: '18',
    funFact: 'The most common noble gas on Earth, used in incandescent light bulbs.',
  ),
  ChemElement(
    atomicNumber: 19, symbol: 'K', name: 'Potassium',
    atomicMass: 39.098, category: 'Alkali metal',
    shells: [2, 8, 8, 1], configuration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹',
    valenceElectrons: 1, period: '4', group: '1',
    funFact: 'Highly reactive metal found in abundance in bananas and seawater.',
  ),
  ChemElement(
    atomicNumber: 20, symbol: 'Ca', name: 'Calcium',
    atomicMass: 40.078, category: 'Alkaline earth metal',
    shells: [2, 8, 8, 2], configuration: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s²',
    valenceElectrons: 2, period: '4', group: '2',
    funFact: 'Essential for biological life, forming the structure of bones and teeth.',
  ),
  ChemElement(
    atomicNumber: 21, symbol: 'Sc', name: 'Scandium',
    atomicMass: 44.956, category: 'Transition metal',
    shells: [2, 8, 9, 2], configuration: '[Ar] 3d¹ 4s²',
    valenceElectrons: 2, period: '4', group: '3',
    funFact: 'Rare earth element used in high-strength aluminum alloys for aerospace.',
  ),
  ChemElement(
    atomicNumber: 22, symbol: 'Ti', name: 'Titanium',
    atomicMass: 47.867, category: 'Transition metal',
    shells: [2, 8, 10, 2], configuration: '[Ar] 3d² 4s²',
    valenceElectrons: 2, period: '4', group: '4',
    funFact: 'Known for its high strength-to-weight ratio and corrosion resistance.',
  ),
  ChemElement(
    atomicNumber: 23, symbol: 'V', name: 'Vanadium',
    atomicMass: 50.942, category: 'Transition metal',
    shells: [2, 8, 11, 2], configuration: '[Ar] 3d³ 4s²',
    valenceElectrons: 2, period: '4', group: '5',
    funFact: 'Adds hardness and thermal stability to steel alloys.',
  ),
  ChemElement(
    atomicNumber: 24, symbol: 'Cr', name: 'Chromium',
    atomicMass: 51.996, category: 'Transition metal',
    shells: [2, 8, 13, 1], configuration: '[Ar] 3d⁵ 4s¹',
    valenceElectrons: 1, period: '4', group: '6',
    funFact: 'The main additive in stainless steel, providing its rust resistance.',
  ),
  ChemElement(
    atomicNumber: 25, symbol: 'Mn', name: 'Manganese',
    atomicMass: 54.938, category: 'Transition metal',
    shells: [2, 8, 13, 2], configuration: '[Ar] 3d⁵ 4s²',
    valenceElectrons: 2, period: '4', group: '7',
    funFact: 'Crucial for steel production and used in common alkaline batteries.',
  ),
  ChemElement(
    atomicNumber: 26, symbol: 'Fe', name: 'Iron',
    atomicMass: 55.845, category: 'Transition metal',
    shells: [2, 8, 14, 2], configuration: '[Ar] 3d⁶ 4s²',
    valenceElectrons: 2, period: '4', group: '8',
    funFact: 'The most common element on Earth by mass, forming the planet\'s core.',
  ),
  ChemElement(
    atomicNumber: 27, symbol: 'Co', name: 'Cobalt',
    atomicMass: 58.933, category: 'Transition metal',
    shells: [2, 8, 15, 2], configuration: '[Ar] 3d⁷ 4s²',
    valenceElectrons: 2, period: '4', group: '9',
    funFact: 'Essential for Vitamin B12 and used in high-performance magnets.',
  ),
  ChemElement(
    atomicNumber: 28, symbol: 'Ni', name: 'Nickel',
    atomicMass: 58.693, category: 'Transition metal',
    shells: [2, 8, 16, 2], configuration: '[Ar] 3d⁸ 4s²',
    valenceElectrons: 2, period: '4', group: '10',
    funFact: 'Resists corrosion and is used in coinage and stainless steel.',
  ),
  ChemElement(
    atomicNumber: 29, symbol: 'Cu', name: 'Copper',
    atomicMass: 63.546, category: 'Transition metal',
    shells: [2, 8, 18, 1], configuration: '[Ar] 3d¹⁰ 4s¹',
    valenceElectrons: 1, period: '4', group: '11',
    funFact: 'Excellent electrical conductor, essential for modern wiring.',
  ),
  ChemElement(
    atomicNumber: 30, symbol: 'Zn', name: 'Zinc',
    atomicMass: 65.38, category: 'Transition metal',
    shells: [2, 8, 18, 2], configuration: '[Ar] 3d¹⁰ 4s²',
    valenceElectrons: 2, period: '4', group: '12',
    funFact: 'Used to galvanize steel to prevent rusting and in brass alloys.',
  ),
  ChemElement(
    atomicNumber: 31, symbol: 'Ga', name: 'Gallium',
    atomicMass: 69.723, category: 'Post-transition metal',
    shells: [2, 8, 18, 3], configuration: '[Ar] 3d¹⁰ 4s² 4p¹',
    valenceElectrons: 3, period: '4', group: '13',
    funFact: 'Melts in your hand. Used in semiconductors like Gallium Arsenide.',
  ),
  ChemElement(
    atomicNumber: 32, symbol: 'Ge', name: 'Germanium',
    atomicMass: 72.63, category: 'Metalloid',
    shells: [2, 8, 18, 4], configuration: '[Ar] 3d¹⁰ 4s² 4p²',
    valenceElectrons: 4, period: '4', group: '14',
    funFact: 'Early semiconductor material used before silicon became dominant.',
  ),
  ChemElement(
    atomicNumber: 33, symbol: 'As', name: 'Arsenic',
    atomicMass: 74.922, category: 'Metalloid',
    shells: [2, 8, 18, 5], configuration: '[Ar] 3d¹⁰ 4s² 4p³',
    valenceElectrons: 5, period: '4', group: '15',
    funFact: 'Famous for its toxicity, it is also used in many metal alloys.',
  ),
  ChemElement(
    atomicNumber: 34, symbol: 'Se', name: 'Selenium',
    atomicMass: 78.971, category: 'Nonmetal',
    shells: [2, 8, 18, 6], configuration: '[Ar] 3d¹⁰ 4s² 4p⁴',
    valenceElectrons: 6, period: '4', group: '16',
    funFact: 'Photoconductive element used in glass production and nutrition.',
  ),
  ChemElement(
    atomicNumber: 35, symbol: 'Br', name: 'Bromine',
    atomicMass: 79.904, category: 'Halogen',
    shells: [2, 8, 18, 7], configuration: '[Ar] 3d¹⁰ 4s² 4p⁵',
    valenceElectrons: 7, period: '4', group: '17',
    funFact: 'The only non-metallic element that exists as a liquid at room temperature.',
  ),
  ChemElement(
    atomicNumber: 36, symbol: 'Kr', name: 'Krypton',
    atomicMass: 83.798, category: 'Noble gas',
    shells: [2, 8, 18, 8], configuration: '[Ar] 3d¹⁰ 4s² 4p⁶',
    valenceElectrons: 8, period: '4', group: '18',
    funFact: 'Used in lighting and photography for a brilliant white light.',
  ),
];
