import 'package:flutter/material.dart';
import 'package:vector_math/vector_math_64.dart';
import '../models/molecule.dart';
import '../theme/app_colors.dart';

final List<Molecule> kMolecules = [
  Molecule(
    name: 'Water',
    formula: 'H₂O',
    shape: 'Bent (104.5°)',
    description: 'Two O–H bonds with two lone pairs on oxygen give water its bent shape and polarity.',
    atoms: [
      MoleculeAtom(element: 'O', color: const Color(0xFFFF4444), radius: 18,
        position: Vector3(0, 0, 0)),
      MoleculeAtom(element: 'H', color: const Color(0xFFEEEEEE), radius: 12,
        position: Vector3(-1.0, -0.8, 0)),
      MoleculeAtom(element: 'H', color: const Color(0xFFEEEEEE), radius: 12,
        position: Vector3( 1.0, -0.8, 0)),
    ],
    bonds: [
      const MoleculeBond(atomA: 0, atomB: 1, order: 1),
      const MoleculeBond(atomA: 0, atomB: 2, order: 1),
    ],
  ),
  Molecule(
    name: 'Carbon dioxide',
    formula: 'CO₂',
    shape: 'Linear (180°)',
    description: 'Two double bonds with no lone pairs on carbon. Linear and non-polar despite polar bonds.',
    atoms: [
      MoleculeAtom(element: 'O', color: const Color(0xFFFF4444), radius: 18,
        position: Vector3(-1.3, 0, 0)),
      MoleculeAtom(element: 'C', color: const Color(0xFF888888), radius: 15,
        position: Vector3( 0,   0,   0)),
      MoleculeAtom(element: 'O', color: const Color(0xFFFF4444), radius: 18,
        position: Vector3( 1.3, 0,   0)),
    ],
    bonds: [
      const MoleculeBond(atomA: 0, atomB: 1, order: 2),
      const MoleculeBond(atomA: 1, atomB: 2, order: 2),
    ],
  ),
  Molecule(
    name: 'Methane',
    formula: 'CH₄',
    shape: 'Tetrahedral (109.5°)',
    description: 'Four identical C–H bonds arranged tetrahedrally. A perfectly symmetrical non-polar molecule.',
    atoms: [
      MoleculeAtom(element: 'C', color: const Color(0xFF888888), radius: 16,
        position: Vector3(0, 0, 0)),
      MoleculeAtom(element: 'H', color: const Color(0xFFEEEEEE), radius: 11,
        position: Vector3( 1.0,  1.0,  1.0)),
      MoleculeAtom(element: 'H', color: const Color(0xFFEEEEEE), radius: 11,
        position: Vector3(-1.0, -1.0,  1.0)),
      MoleculeAtom(element: 'H', color: const Color(0xFFEEEEEE), radius: 11,
        position: Vector3(-1.0,  1.0, -1.0)),
      MoleculeAtom(element: 'H', color: const Color(0xFFEEEEEE), radius: 11,
        position: Vector3( 1.0, -1.0, -1.0)),
    ],
    bonds: [
      const MoleculeBond(atomA: 0, atomB: 1, order: 1),
      const MoleculeBond(atomA: 0, atomB: 2, order: 1),
      const MoleculeBond(atomA: 0, atomB: 3, order: 1),
      const MoleculeBond(atomA: 0, atomB: 4, order: 1),
    ],
  ),
  Molecule(
    name: 'Ammonia',
    formula: 'NH₃',
    shape: 'Trigonal pyramidal (107°)',
    description: 'Three bonds and one lone pair (not shown) compresses the angle to 107°.',
    atoms: [
      MoleculeAtom(element: 'N', color: const Color(0xFF3333AA), radius: 16,
        position: Vector3(0, 0, 0)),
      MoleculeAtom(element: 'H', color: const Color(0xFFEEEEEE), radius: 11,
        position: Vector3(1.0, -0.4, 0)),
      MoleculeAtom(element: 'H', color: const Color(0xFFEEEEEE), radius: 11,
        position: Vector3(-0.5, -0.4, 0.866)),
      MoleculeAtom(element: 'H', color: const Color(0xFFEEEEEE), radius: 11,
        position: Vector3(-0.5, -0.4, -0.866)),
    ],
    bonds: [
      const MoleculeBond(atomA: 0, atomB: 1, order: 1),
      const MoleculeBond(atomA: 0, atomB: 2, order: 1),
      const MoleculeBond(atomA: 0, atomB: 3, order: 1),
    ],
  ),
  Molecule(
    name: 'Ethane',
    formula: 'C₂H₆',
    shape: 'Tetrahedral center (109.5°)',
    description: 'A simple alkane with a single carbon-carbon bond.',
    atoms: [
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10.0, position: Vector3(-0.77, 0, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10.0, position: Vector3(0.77, 0, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(-1.15, 0.7, 0.7)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(-1.15, 0.7, -0.7)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(-1.15, -1.0, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(1.15, -0.7, 0.7)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(1.15, -0.7, -0.7)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(1.15, 1.0, 0)),
    ],
    bonds: [
      const MoleculeBond(atomA: 0, atomB: 1, order: 1),
      const MoleculeBond(atomA: 0, atomB: 2, order: 1),
      const MoleculeBond(atomA: 0, atomB: 3, order: 1),
      const MoleculeBond(atomA: 0, atomB: 4, order: 1),
      const MoleculeBond(atomA: 1, atomB: 5, order: 1),
      const MoleculeBond(atomA: 1, atomB: 6, order: 1),
      const MoleculeBond(atomA: 1, atomB: 7, order: 1),
    ],
  ),
  Molecule(
    name: 'Ethanol',
    formula: 'C₂H₅OH',
    shape: 'Bent at Oxygen',
    description: 'The alcohol found in beverages, containing a hydroxyl group.',
    atoms: [
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10.0, position: Vector3(-1.0, 0, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10.0, position: Vector3(0.5, 0, 0)),
      MoleculeAtom(element: 'O', color: AppColors.orbitalD, radius: 9.0, position: Vector3(1.2, 1.0, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(2.1, 1.0, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(-1.4, 0.7, 0.7)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(-1.4, 0.7, -0.7)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(-1.4, -1.0, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(0.8, -0.7, 0.7)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(0.8, -0.7, -0.7)),
    ],
    bonds: [
      const MoleculeBond(atomA: 0, atomB: 1, order: 1),
      const MoleculeBond(atomA: 1, atomB: 2, order: 1),
      const MoleculeBond(atomA: 2, atomB: 3, order: 1),
      const MoleculeBond(atomA: 0, atomB: 4, order: 1),
      const MoleculeBond(atomA: 0, atomB: 5, order: 1),
      const MoleculeBond(atomA: 0, atomB: 6, order: 1),
      const MoleculeBond(atomA: 1, atomB: 7, order: 1),
      const MoleculeBond(atomA: 1, atomB: 8, order: 1),
    ],
  ),
  Molecule(
    name: 'Benzene',
    formula: 'C₆H₆',
    shape: 'Planar Hexagonal',
    description: 'A stable aromatic ring with delocalized pi electrons.',
    atoms: [
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10.0, position: Vector3(0, 1.4, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10.0, position: Vector3(1.21, 0.7, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10.0, position: Vector3(1.21, -0.7, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10.0, position: Vector3(0, -1.4, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10.0, position: Vector3(-1.21, -0.7, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10.0, position: Vector3(-1.21, 0.7, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(0, 2.48, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(2.15, 1.24, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(2.15, -1.24, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(0, -2.48, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(-2.15, -1.24, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6.0, position: Vector3(-2.15, 1.24, 0)),
    ],
    bonds: [
      const MoleculeBond(atomA: 0, atomB: 1, order: 2),
      const MoleculeBond(atomA: 1, atomB: 2, order: 1),
      const MoleculeBond(atomA: 2, atomB: 3, order: 2),
      const MoleculeBond(atomA: 3, atomB: 4, order: 1),
      const MoleculeBond(atomA: 4, atomB: 5, order: 2),
      const MoleculeBond(atomA: 5, atomB: 0, order: 1),
      const MoleculeBond(atomA: 0, atomB: 6, order: 1),
      const MoleculeBond(atomA: 1, atomB: 7, order: 1),
      const MoleculeBond(atomA: 2, atomB: 8, order: 1),
      const MoleculeBond(atomA: 3, atomB: 9, order: 1),
      const MoleculeBond(atomA: 4, atomB: 10, order: 1),
      const MoleculeBond(atomA: 5, atomB: 11, order: 1),
    ],
  ),
  Molecule(
    name: 'Aspirin',
    formula: 'C₉H₈O₄',
    shape: 'Complex (Planar Ring + Extensions)',
    description: 'Acetylsalicylic acid, the common pain reliever.',
    atoms: [
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10, position: Vector3(0, 0, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10, position: Vector3(1.2, 0.7, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10, position: Vector3(1.2, 2.1, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10, position: Vector3(0, 2.8, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10, position: Vector3(-1.2, 2.1, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10, position: Vector3(-1.2, 0.7, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10, position: Vector3(0, -1.5, 0)),
      MoleculeAtom(element: 'O', color: AppColors.orbitalD, radius: 9, position: Vector3(1.1, -2.1, 0)),
      MoleculeAtom(element: 'O', color: AppColors.orbitalD, radius: 9, position: Vector3(-1.1, -2.1, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6, position: Vector3(-1.1, -3.1, 0)),
      MoleculeAtom(element: 'O', color: AppColors.orbitalD, radius: 9, position: Vector3(2.5, 0, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10, position: Vector3(3.7, 0, 0)),
      MoleculeAtom(element: 'O', color: AppColors.orbitalD, radius: 9, position: Vector3(4.3, 1.1, 0)),
      MoleculeAtom(element: 'C', color: AppColors.orbitalS, radius: 10, position: Vector3(4.4, -1.2, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6, position: Vector3(2.1, 2.7, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6, position: Vector3(0, 3.8, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6, position: Vector3(-2.1, 2.7, 0)),
      MoleculeAtom(element: 'H', color: AppColors.textSecondary, radius: 6, position: Vector3(-2.1, 0.2, 0)),
    ],
    bonds: [
      const MoleculeBond(atomA: 0, atomB: 1, order: 1),
      const MoleculeBond(atomA: 1, atomB: 2, order: 2),
      const MoleculeBond(atomA: 2, atomB: 3, order: 1),
      const MoleculeBond(atomA: 3, atomB: 4, order: 2),
      const MoleculeBond(atomA: 4, atomB: 5, order: 1),
      const MoleculeBond(atomA: 5, atomB: 0, order: 2),
      const MoleculeBond(atomA: 0, atomB: 6, order: 1),
      const MoleculeBond(atomA: 6, atomB: 7, order: 2),
      const MoleculeBond(atomA: 6, atomB: 8, order: 1),
      const MoleculeBond(atomA: 8, atomB: 9, order: 1),
      const MoleculeBond(atomA: 1, atomB: 10, order: 1),
      const MoleculeBond(atomA: 10, atomB: 11, order: 1),
      const MoleculeBond(atomA: 11, atomB: 12, order: 2),
      const MoleculeBond(atomA: 11, atomB: 13, order: 1),
      const MoleculeBond(atomA: 2, atomB: 14, order: 1),
      const MoleculeBond(atomA: 3, atomB: 15, order: 1),
      const MoleculeBond(atomA: 4, atomB: 16, order: 1),
      const MoleculeBond(atomA: 5, atomB: 17, order: 1),
    ],
  ),
];
